# Generated by Django 6.0.5 on 2026-07-01 22:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knjiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('zanr', models.CharField(blank=True, max_length=255, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('godina_izdanja', models.PositiveSmallIntegerField()),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField(blank=True, null=True)),
                ('vidljiva', models.BooleanField(default=True)),
                ('datum_pisanja', models.DateField(auto_now_add=True)),
                ('ocjena', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knjiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.knjiga')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ocjena__gte', 1), ('ocjena__lte', 5)), name='ocjena_between_1_and_5')],
                'unique_together': {('korisnik', 'knjiga')},
            },
        ),
    ]
