# Generated by Django 6.0.5 on 2026-06-10 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knjiga',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recenzija',
            name='knjiga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.knjiga'),
        ),
        migrations.AddField(
            model_name='recenzija',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='recenzija',
            constraint=models.CheckConstraint(condition=models.Q(('ocjena__gte', 1), ('ocjena__lte', 5)), name='ocjena_between_1_and_5'),
        ),
        migrations.AlterUniqueTogether(
            name='recenzija',
            unique_together={('korisnik', 'knjiga')},
        ),
    ]
